### ISSUE TITLE
it's good looking platform - love the wordpress woocom experience - can you also add 'ACF - Advanced Custom Fields' like module?

### ISSUE THREAD

**Issue by uamin** [CromwellCMS/Cromwell#155]
it's good looking platform - love the wordpress woocom experience - can you also add 'ACF - Advanced Custom Fields' like module? It will greatly help with creating new fields

**Comment by eilrix** [comment]
Closed by https://github.com/CromwellCMS/Cromwell/pull/159
Custom fields implemented via database entity meta tables. All meta is SQL queryable
