### ISSUE TITLE
Payment Options

### ISSUE THREAD

**Issue by adrian29630** [CromwellCMS/Cromwell#157]
You really do need to add PayPal as another option

**Comment by gamedevsam** [comment]
If you care about it, open a PR. That's how open source works.

**Comment by eilrix** [comment]
Agreed about PayPal. I'll look into it this or next week.
In general CMS payment options are extendable by plugins, so other methods could be relatively easily added. 
Here is Stripe example https://github.com/CromwellCMS/Cromwell/blob/master/plugins/stripe/src/backend/actions/create-payment.action.ts
