### ISSUE TITLE
Sortable menu items in Main menu plugin

### ISSUE THREAD

**Issue by mraf** [CromwellCMS/Cromwell#181]
Please enable reorder elements in a menu item list using the mouse. Click on and drag an element to a new spot within the list, and the other items will adjust to fit.

**Comment by eilrix** [comment]
That would be much better to use. I'll look into that
Btw admin-panel package already exports draggable list component, so it would be something like
```tsx
import { DraggableList } from  '@cromwell/admin-panel';
<DraggableList
  data={[]}
  onChange={()=>{}}
  component={Item}
/>
```

**Comment by mraf** [comment]
Thanks! Good reference for another pluggins which can use this component.
