### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by robertlansing** [CromwellCMS/Cromwell#204]
Hello,
It looks like the repo hasn’t had an update in awhile. Is it still being developed or supported? Perhaps elsewhere? I would love to get involved in some way. I hate Wordpress and need a viable alternative. 

Thank you,
Robert

**Comment by Messa1** [comment]
@robertlansing as I see there are working on it -> 
https://github.com/CromwellCMS/Cromwell/commits/master last commit -> Feb 15, 2023
https://github.com/CromwellCMS/Cromwell/commits/3.0 last commit -> Jun 21, 2023

**Comment by mraf** [comment]
Hello, yes still in developement, switch to v3.0 branch. Support is provided on Discord
