### ISSUE TITLE
Example applications not available

### ISSUE THREAD

**Issue by kruligh** [CromwellCMS/Cromwell#205]
In documentation there is page with examples - https://cromwellcms.com/docs/overview/intro/#examples but urls are not available.

Cloudflare returns 502 response (https://demo-store.cromwellcms.com/)

In meanwhile `main.css` file is hosted correctly. (https://demo-store.cromwellcms.com/cdn-cgi/styles/main.css)

Looks like some broken build or some server miss configuration.

Does anyone can resurrect examples? :P

**Comment by eilrix** [comment]
Thanks for reporting, it's back online
